import {
  ProtectionFeatureStatus,
  ProtectionFeatureType,
} from '@prisma/client';

export interface BuiltInProtectionFeature {
  featureType: ProtectionFeatureType;
  featureName: string;
  featureCode: string;
  scene: string;
  featurePoint: string;
  matcher: 'regex';
  hitRate: number;
  priority: number;
  expression: string;
  sampleValue: string;
  status: ProtectionFeatureStatus;
  description: string;
}

const maskingFeature = (
  feature: Omit<
    BuiltInProtectionFeature,
    'featureType' | 'matcher' | 'status'
  >,
): BuiltInProtectionFeature => ({
  ...feature,
  featureType: ProtectionFeatureType.MASKING,
  matcher: 'regex',
  status: ProtectionFeatureStatus.ACTIVE,
});

const encryptionFeature = (
  feature: Omit<
    BuiltInProtectionFeature,
    'featureType' | 'matcher' | 'status'
  >,
): BuiltInProtectionFeature => ({
  ...feature,
  featureType: ProtectionFeatureType.ENCRYPTION,
  matcher: 'regex',
  status: ProtectionFeatureStatus.ACTIVE,
});

export const RETIRED_BUILT_IN_MASKING_FEATURE_CODES = [
  'MASK_PHONE',
  'MASK_CONSECUTIVE_ASTERISKS',
  'MASK_CONSECUTIVE_HASHES',
  'MASK_PHONE_MIDDLE',
  'MASK_PHONE_COUNTRY_CODE',
  'MASK_LANDLINE',
  'MASK_ID_NUMBER',
  'MASK_BANK_CARD',
  'MASK_EMAIL_LOCAL_PART',
  'MASK_EMAIL_LOCAL_PART_FULL',
  'MASK_CHINESE_NAME',
  'MASK_CHINESE_NAME_SURNAME',
  'MASK_ADDRESS',
  'MASK_IPV4',
  'MASK_LICENSE_PLATE',
  'MASK_BIRTH_DATE',
  'MASK_DATE_COMPONENTS',
  'MASK_ACCOUNT',
  'MASK_SOCIAL_CREDIT_CODE',
  'MASK_REDACTED_TOKEN',
  'MASK_MAC_ADDRESS',
  'MASK_FULL_SYMBOL',
] as const;

export const BUILT_IN_PROTECTION_FEATURES: readonly BuiltInProtectionFeature[] = [
  maskingFeature({
    featureName: '星号脱敏',
    featureCode: 'MASK_ASTERISK',
    scene: '星号*',
    featurePoint: '字段值任意位置出现至少一个半角星号',
    hitRate: 100,
    priority: 10,
    expression: '^[\\s\\S]*\\*[\\s\\S]*$',
    sampleValue: '任意内容*任意内容',
    description: '不区分业务类型，统一识别一个或多个 * 脱敏符号。',
  }),
  maskingFeature({
    featureName: '井号脱敏',
    featureCode: 'MASK_HASH',
    scene: '井号#',
    featurePoint: '字段值任意位置出现至少一个半角井号',
    hitRate: 100,
    priority: 20,
    expression: '^[\\s\\S]*#[\\s\\S]*$',
    sampleValue: '任意内容#任意内容',
    description: '不区分业务类型，统一识别一个或多个 # 脱敏符号。',
  }),
  encryptionFeature({
    featureName: 'MD5 摘要指纹',
    featureCode: 'ENC_DIGEST_MD5',
    scene: '摘要哈希',
    featurePoint: '32 位十六进制摘要串',
    hitRate: 88,
    priority: 10,
    expression: '^[A-Fa-f0-9]{32}$',
    sampleValue: 'd41d8cd98f00b204e9800998ecf8427e',
    description: '仅识别 MD5 常见文本形态；无法证明具体算法或安全强度。',
  }),
  encryptionFeature({
    featureName: 'SHA-1 摘要指纹',
    featureCode: 'ENC_DIGEST_SHA1',
    scene: '摘要哈希',
    featurePoint: '40 位十六进制摘要串',
    hitRate: 90,
    priority: 20,
    expression: '^[A-Fa-f0-9]{40}$',
    sampleValue: 'da39a3ee5e6b4b0d3255bfef95601890afd80709',
    description: '识别 SHA-1 的常见十六进制序列化形态。',
  }),
  encryptionFeature({
    featureName: 'SHA-256 / SM3 摘要指纹',
    featureCode: 'ENC_DIGEST_256',
    scene: '摘要哈希',
    featurePoint: '64 位十六进制摘要串',
    hitRate: 92,
    priority: 30,
    expression: '^[A-Fa-f0-9]{64}$',
    sampleValue: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    description: 'SHA-256 与 SM3 的文本长度相同，仅凭值形态不能区分算法。',
  }),
  encryptionFeature({
    featureName: 'SHA-384 摘要指纹',
    featureCode: 'ENC_DIGEST_SHA384',
    scene: '摘要哈希',
    featurePoint: '96 位十六进制摘要串',
    hitRate: 92,
    priority: 40,
    expression: '^[A-Fa-f0-9]{96}$',
    sampleValue: '38b060a751ac96384cd9327eb1b1e36a21fdb71114be07434c0cc7bf63f6e1da274edebfe76f65fbd51ad2f14898b95b',
    description: '识别 SHA-384 的常见十六进制序列化形态。',
  }),
  encryptionFeature({
    featureName: 'SHA-512 摘要指纹',
    featureCode: 'ENC_DIGEST_SHA512',
    scene: '摘要哈希',
    featurePoint: '128 位十六进制摘要串',
    hitRate: 94,
    priority: 50,
    expression: '^[A-Fa-f0-9]{128}$',
    sampleValue: 'cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e',
    description: '识别 SHA-512 的常见十六进制序列化形态。',
  }),
  encryptionFeature({
    featureName: 'PostgreSQL MD5 口令哈希',
    featureCode: 'ENC_PASSWORD_POSTGRES_MD5',
    scene: '摘要哈希',
    featurePoint: '以 md5 开头并跟随 32 位十六进制摘要',
    hitRate: 98,
    priority: 55,
    expression: '^md5[A-Fa-f0-9]{32}$',
    sampleValue: 'md55f4dcc3b5aa765d61d8327deb882cf99',
    description: '识别 PostgreSQL 旧式 MD5 口令验证值。',
  }),
  encryptionFeature({
    featureName: 'MySQL Native Password 哈希',
    featureCode: 'ENC_PASSWORD_MYSQL_NATIVE',
    scene: '摘要哈希',
    featurePoint: '星号开头的 40 位大写十六进制双 SHA-1 摘要',
    hitRate: 98,
    priority: 56,
    expression: '^\\*[A-F0-9]{40}$',
    sampleValue: '*94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29',
    description: '识别 MySQL 4.1 及以后版本曾使用的 native password 格式。',
  }),
  encryptionFeature({
    featureName: 'SQL Server 口令哈希',
    featureCode: 'ENC_PASSWORD_SQL_SERVER',
    scene: '摘要哈希',
    featurePoint: '以 0x0100 或 0x0200 开头的 SQL Server 口令哈希',
    hitRate: 98,
    priority: 57,
    expression: '^0x0(?:100|200)[A-Fa-f0-9]{40,}$',
    sampleValue: '0x0200A1B2C3D4E5F60718293A4B5C6D7E8F90123456789ABCDEF0123456789ABC',
    description: '识别 SQL Server 登录口令的版本化二进制十六进制表示。',
  }),
  encryptionFeature({
    featureName: 'bcrypt 口令哈希',
    featureCode: 'ENC_PASSWORD_BCRYPT',
    scene: '摘要哈希',
    featurePoint: '以 $2a$、$2b$ 或 $2y$ 开头的 bcrypt 模块化格式',
    hitRate: 98,
    priority: 60,
    expression: '^\\$2[aby]\\$\\d{2}\\$[./A-Za-z0-9]{53}$',
    sampleValue: '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6Ttx5lH1ydL94gFQ2M2XwzQ4yYQeK',
    description: '包含算法版本、成本参数、盐和哈希值。',
  }),
  encryptionFeature({
    featureName: 'Argon2 口令哈希',
    featureCode: 'ENC_PASSWORD_ARGON2',
    scene: '摘要哈希',
    featurePoint: 'Argon2d、Argon2i 或 Argon2id 的 PHC 字符串格式',
    hitRate: 98,
    priority: 70,
    expression: '^\\$argon2(?:id|i|d)\\$v=\\d+\\$m=\\d+,t=\\d+,p=\\d+\\$[A-Za-z0-9+/]+={0,2}\\$[A-Za-z0-9+/]+={0,2}$',
    sampleValue: '$argon2id$v=19$m=65536,t=3,p=4$c29tZXNhbHQ$YWJjZGVmZ2hpamtsbW5vcA',
    description: '识别带版本与内存、迭代、并行度参数的 PHC 格式。',
  }),
  encryptionFeature({
    featureName: 'scrypt 口令哈希',
    featureCode: 'ENC_PASSWORD_SCRYPT',
    scene: '摘要哈希',
    featurePoint: '包含 ln、r、p 参数的 scrypt PHC 字符串格式',
    hitRate: 98,
    priority: 80,
    expression: '^\\$scrypt\\$ln=\\d+,r=\\d+,p=\\d+\\$[A-Za-z0-9+/]+={0,2}\\$[A-Za-z0-9+/]+={0,2}$',
    sampleValue: '$scrypt$ln=16,r=8,p=1$c29tZXNhbHQ$YWJjZGVmZ2hpamtsbW5vcA',
    description: '识别标准参数化 scrypt 口令哈希表示。',
  }),
  encryptionFeature({
    featureName: 'PBKDF2 口令哈希',
    featureCode: 'ENC_PASSWORD_PBKDF2',
    scene: '摘要哈希',
    featurePoint: '含摘要算法、迭代次数、盐和结果的 PBKDF2 格式',
    hitRate: 96,
    priority: 90,
    expression: '^pbkdf2_(?:sha256|sha512)\\$\\d+\\$[A-Za-z0-9./+_-]+\\$[A-Za-z0-9+/]+={0,2}$',
    sampleValue: 'pbkdf2_sha256$600000$somesalt$YWJjZGVmZ2hpamtsbW5vcA==',
    description: '覆盖 Django 等框架常用的 PBKDF2 序列化格式。',
  }),
  encryptionFeature({
    featureName: 'Unix SHA-crypt 口令哈希',
    featureCode: 'ENC_PASSWORD_SHA_CRYPT',
    scene: '摘要哈希',
    featurePoint: '以 $5$ 或 $6$ 开头的 SHA-256/SHA-512 crypt 格式',
    hitRate: 96,
    priority: 100,
    expression: '^\\$(?:5|6)\\$(?:rounds=\\d+\\$)?[./A-Za-z0-9]{1,16}\\$[./A-Za-z0-9]{20,86}$',
    sampleValue: '$6$rounds=5000$somesalt$LkoZ3Yw3JmNHV5xV7u5q9QfYcV2jGmP5N4hK8sR2xE1',
    description: '识别 Linux shadow 等场景中的 SHA-crypt 模块化格式。',
  }),
  encryptionFeature({
    featureName: 'LDAP Salted SHA 哈希',
    featureCode: 'ENC_PASSWORD_LDAP_SSHA',
    scene: '摘要哈希',
    featurePoint: '以 {SSHA}、{SSHA256}、{SSHA384} 或 {SSHA512} 标记开头',
    hitRate: 98,
    priority: 105,
    expression: '^\\{SSHA(?:256|384|512)?\\}[A-Za-z0-9+/]{20,}={0,2}$',
    sampleValue: '{SSHA}jLIjfQZ5yojbZGTqxg2pY0VROWQ0NDAx',
    description: '识别 LDAP 目录中常见的带盐 SHA 系列口令哈希表示。',
  }),
  encryptionFeature({
    featureName: 'OpenSSL Salted 密文',
    featureCode: 'ENC_OPENSSL_SALTED',
    scene: '对称加密',
    featurePoint: 'Base64 解码后以 Salted__ 开头的 OpenSSL 密文',
    hitRate: 96,
    priority: 110,
    expression: '^U2FsdGVkX1[A-Za-z0-9+/]{16,}={0,2}$',
    sampleValue: 'U2FsdGVkX1+Qx0kVqR2n5bY8dX3pJ7mL9sA1cE4gH6I=',
    description: '识别 openssl enc 命令常见的带盐 Base64 输出。',
  }),
  encryptionFeature({
    featureName: 'Fernet 令牌',
    featureCode: 'ENC_TOKEN_FERNET',
    scene: '令牌票据',
    featurePoint: '以 gAAAAA 开头的 URL-safe Base64 Fernet 令牌',
    hitRate: 97,
    priority: 120,
    expression: '^gAAAAA[A-Za-z0-9_-]{70,}={0,2}$',
    sampleValue: 'gAAAAABmT7ZxQ2vL8cD1nH5jK9sR4wE6yU0iO3pA7fG2hJ5kL8zX1cV4bN6mQ9rS2tW5yZ8aB1cD4eF7gH0=',
    description: '识别 Python cryptography 等实现生成的 Fernet 对称加密令牌。',
  }),
  encryptionFeature({
    featureName: 'JWT 紧凑令牌',
    featureCode: 'ENC_TOKEN_JWT',
    scene: '令牌票据',
    featurePoint: '由三个 Base64URL 分段组成且头部以 eyJ 开头',
    hitRate: 94,
    priority: 130,
    expression: '^eyJ[A-Za-z0-9_-]+\\.eyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+$',
    sampleValue: 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c',
    description: 'JWT 通常是签名令牌而非加密密文，此规则用于识别受保护票据形态。',
  }),
  encryptionFeature({
    featureName: 'JWE 紧凑密文',
    featureCode: 'ENC_TOKEN_JWE',
    scene: '令牌票据',
    featurePoint: '由五个 Base64URL 分段组成的 JSON Web Encryption',
    hitRate: 98,
    priority: 140,
    expression: '^[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]*\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+$',
    sampleValue: 'eyJhbGciOiJSU0EtT0FFUCJ9.ZW5jcnlwdGVka2V5.aXYxMjM0NTY.Y2lwaGVydGV4dA.dGFnMTIzNDU2',
    description: '识别 JWE 的受保护头、密钥、IV、密文和认证标签五段结构。',
  }),
  encryptionFeature({
    featureName: '加密私钥 PEM',
    featureCode: 'ENC_PEM_PRIVATE_KEY',
    scene: '非对称加密',
    featurePoint: '带 ENCRYPTED PRIVATE KEY 头尾的 PEM 文本',
    hitRate: 99,
    priority: 150,
    expression: '^-----BEGIN ENCRYPTED PRIVATE KEY-----[\\s\\S]+-----END ENCRYPTED PRIVATE KEY-----$',
    sampleValue: '-----BEGIN ENCRYPTED PRIVATE KEY-----\nMIIBvTBXBgkqhkiG9w0BBQ0wSjAp\n-----END ENCRYPTED PRIVATE KEY-----',
    description: '识别 PKCS#8 加密私钥容器，不匹配普通公钥或未加密私钥。',
  }),
  encryptionFeature({
    featureName: '传统 PEM 加密私钥',
    featureCode: 'ENC_PEM_LEGACY_PRIVATE_KEY',
    scene: '非对称加密',
    featurePoint: '私钥 PEM 内含 Proc-Type: 4,ENCRYPTED 加密标记',
    hitRate: 99,
    priority: 155,
    expression: '^-----BEGIN (?:RSA |EC )?PRIVATE KEY-----[\\s\\S]*Proc-Type: 4,ENCRYPTED[\\s\\S]+-----END (?:RSA |EC )?PRIVATE KEY-----$',
    sampleValue: '-----BEGIN RSA PRIVATE KEY-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: AES-256-CBC,0123456789ABCDEF\nYWJjZGVmZ2hpamts\n-----END RSA PRIVATE KEY-----',
    description: '识别 OpenSSL 传统 PEM 格式中通过头部声明加密的 RSA 或 EC 私钥。',
  }),
  encryptionFeature({
    featureName: 'OpenPGP 装甲密文',
    featureCode: 'ENC_PGP_MESSAGE',
    scene: '非对称加密',
    featurePoint: '带 PGP MESSAGE 头尾的 ASCII Armor 密文',
    hitRate: 99,
    priority: 160,
    expression: '^-----BEGIN PGP MESSAGE-----[\\s\\S]+-----END PGP MESSAGE-----$',
    sampleValue: '-----BEGIN PGP MESSAGE-----\nwcBMA0R2bXNhbXBsZQ\n-----END PGP MESSAGE-----',
    description: '识别 OpenPGP ASCII Armor 消息容器。',
  }),
  encryptionFeature({
    featureName: '版本化 AEAD 密文',
    featureCode: 'ENC_AEAD_COMPOSITE',
    scene: '对称加密',
    featurePoint: '由版本、IV、密文和认证标签组成的冒号分隔值',
    hitRate: 90,
    priority: 170,
    expression: '^v\\d+:[A-Za-z0-9_-]{12,}:[A-Za-z0-9_-]{16,}:[A-Za-z0-9_-]{16,}$',
    sampleValue: 'v1:YWJjZGVmZ2hpamts:Y2lwaGVydGV4dDEyMzQ1Ng:dGFnMTIzNDU2Nzg5MA',
    description: '识别应用中常见的版本化 AES-GCM/ChaCha20-Poly1305 组合封装。',
  }),
  encryptionFeature({
    featureName: '显式 ENC 密文包装',
    featureCode: 'ENC_WRAPPED_VALUE',
    scene: '编码封装',
    featurePoint: '由 ENC、ENCRYPTED、AES 或 SM4 标记包裹的密文',
    hitRate: 94,
    priority: 180,
    expression: '^(?:ENC|ENCRYPTED|AES|SM4)[({:][A-Za-z0-9+/_=-]{16,}[)}]?$',
    sampleValue: 'ENC(Y2lwaGVydGV4dF9zYW1wbGU=)',
    description: '识别配置中心、ORM 或应用协议中的显式密文包装格式。',
  }),
  encryptionFeature({
    featureName: '长十六进制密文或摘要',
    featureCode: 'ENC_HEX_LONG',
    scene: '编码封装',
    featurePoint: '至少 48 位的偶数长度十六进制数据',
    hitRate: 82,
    priority: 190,
    expression: '^(?:[A-Fa-f0-9]{2}){24,}$',
    sampleValue: '8f2a5594902f1d7e4b0c9a8835d6ef127ad9c04eb2f839af',
    description: '通用兜底规则，可能同时命中摘要、密文或二进制编码，需结合字段语义复核。',
  }),
  encryptionFeature({
    featureName: '长 Base64 密文或编码',
    featureCode: 'ENC_BASE64_LONG',
    scene: '编码封装',
    featurePoint: '至少 64 个字符且满足标准 Base64 分组',
    hitRate: 78,
    priority: 200,
    expression: '^(?:[A-Za-z0-9+/]{4}){16,}(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$',
    sampleValue: 'VGhpcyBpcyBhIGxvbmcgZW5jb2RlZCBvciBlbmNyeXB0ZWQgdmFsdWUgd2l0aCBmaXhlZCBsZW5ndGgu',
    description: '低置信度兜底规则；Base64 只是编码，不能单独证明数据已经加密。',
  }),
];
